### ISSUE TITLE
tuya_bulb_control.exceptions.AuthorizedError: 1004 -> Sign invalid

### ISSUE THREAD

**Issue by gabriel-per** [Octoober/tuya-bulb-control#5]
Hello!

This error happens immediately upon running the example code. Region is set to US, and client ID, client secret and device ID are all OK. PC is also connected to the same network as the bulb, if that is relevant.

Full error log:
Traceback (most recent call last):
  File "c:\Users\XXX\Documents\CodingStudies\playground\python\smart-light-piano\main.py", line 9, in <module>
    bulb = Bulb(
           ^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\tuya_bulb_control\bulb.py", line 23, in __init__
    super().__init__(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\tuya_bulb_control\_tuya_api.py", line 25, in __init__
    self.__access_token = self.__token()
                          ^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\tuya_bulb_control\_tuya_api.py", line 102, in __token
    raise AuthorizedError(
tuya_bulb_control.exceptions.AuthorizedError: 1004 -> Sign invalid

**Comment by 14hi0n** [comment]
I no longer have any Tuya devices and have no way to fully test performance. If someone finds a solution, I would appreciate a Pull Request.😔
